# Sample VSTS CI file
variables:
  Build.Repository.Clean: true
  targetFramework: netcoreapp2.0

# Three phases for each of the three OSes we want to run on
phases:
  - phase: Windows
    queue:
      name: Helix
      parallel: 2
      matrix:
        debug_conf:
          _BuildConfig: Debug
        ${{ if notIn(variables['Build.Reason'], 'PullRequest') }}:
          release_conf:
            _BuildConfig: Release
    steps:
    - template: eng/build.yml

  - phase: OSX
    queue:
      name: Hosted macOS Preview
      parallel: 2
      matrix:
        debug_conf:
          _BuildConfig: Debug
        ${{ if notIn(variables['Build.Reason'], 'PullRequest') }}:
          release_conf:
            _BuildConfig: Release
    steps:
    - template: eng/build.yml

  - phase: Linux
    queue:
      name: DotNetCore-Linux
      parallel: 2
      matrix:
        debug_conf:
          _BuildConfig: Debug
        ${{ if notIn(variables['Build.Reason'], 'PullRequest') }}:
          release_conf:
            _BuildConfig: Release
    steps:
    - template: eng/build.yml