variables:
  Build.Repository.Clean: true
  targetFramework: netcoreapp2.0
  _HelixType: build/product
  _HelixSource: pr/dotnet/arcade-minimalci-sample/$(Build.SourceBranch)

trigger:
- master

# To be added in the future when VSTS supports this feature
# pr:
# - master

# Three phases for each of the three OSes we want to run on
phases:
- template: /eng/common/templates/phases/base.yml
  parameters:
    agentOs: Windows_NT
    name: Windows_NT
    enableTelemetry: true
    queue:
      name: Helix
      parallel: 99
      matrix:
        debug_configuration:
          _BuildConfig: Debug
        release_configuration:
          _BuildConfig: Release
    steps:
    - script: eng\common\cibuild.cmd
        -configuration $(_BuildConfig)
        -prepareMachine
      name: Build
      displayName: Build
      condition: succeeded()
    - template: /eng/common/templates/steps/helix-publish.yml
      parameters:
        HelixSource: $(_HelixSource)
        HelixType: $(_HelixType)
        HelixTargetQueues: Windows.10.Amd64.Open;Windows.7.Amd64.Open
        HelixAccessToken: $(HelixTestAccessToken)
        CorrelationPayloadDirectory: .\.dotnet
        WorkItemDirectory: $(Build.SourcesDirectory)/HelloTests
        WorkItemCommand: "%HELIX_CORRELATION_PAYLOAD% dotnet xunit"
        EnableXUnitReporter: true
        Condition: eq(variables['_BuildConfig'], 'Debug')
    variables:
      _HelixBuildConfig: $(_BuildConfig)

- template: /eng/common/templates/phases/base.yml
  parameters:
    agentOs: OSX
    name: OSX
    enableTelemetry: true
    queue:
      name: Hosted macOS Preview
      parallel: 99
      matrix:
        debug_configuration:
          _BuildConfig: Debug
        release_configuration:
          _BuildConfig: Release
    steps:
    - script: eng/common/cibuild.sh
        --configuration $(_BuildConfig)
        --prepareMachine
      name: Build
      displayName: Build
      condition: succeeded()
    - template: /eng/common/templates/steps/helix-publish.yml
      parameters:
        HelixSource: $(_HelixSource)
        HelixType: $(_HelixType)
        HelixTargetQueues: OSX.1012.Amd64
        HelixAccessToken: $(HelixTestAccessToken)
        CorrelationPayloadDirectory: ./.dotnet
        WorkItemDirectory: $(Build.SourcesDirectory)/HelloTests
        WorkItemCommand: $HELIX_CORRELATION_PAYLOAD dotnet xunit
        EnableXUnitReporter: true
        Condition: eq(variables['_BuildConfig'], 'Debug')
    variables:
      _HelixBuildConfig: $(_BuildConfig)

- template: /eng/common/templates/phases/base.yml
  parameters:
    agentOs: Linux
    name: Linux
    enableTelemetry: true
    queue:
      name: DotNetCore-Linux
      parallel: 99
      matrix:
        debug_configuration:
          _BuildConfig: Debug
        release_configuration:
          _BuildConfig: Release
    steps:
    - task: DotNetCoreInstaller@0
      inputs:
        version: 2.1.401
    - script: eng/common/cibuild.sh
        --configuration $(_BuildConfig)
        --prepareMachine
      name: Build
      displayName: Build
      condition: succeeded()
    - template: /eng/common/templates/steps/helix-publish.yml
      parameters:
        HelixSource: $(_HelixSource)
        HelixType: $(_HelixType)
        HelixTargetQueues: Debian.9.Amd64.Open;Fedora.27.Amd64.Open;RedHat.74.Amd64.Open;Ubuntu.1604.Amd64.Open
        HelixAccessToken: $(HelixTestAccessToken)
        CorrelationPayloadDirectory: ./.dotnet
        WorkItemDirectory: $(Build.SourcesDirectory)/HelloTests
        WorkItemCommand: $HELIX_CORRELATION_PAYLOAD dotnet xunit
        EnableXUnitReporter: true
        Condition: eq(variables['_BuildConfig'], 'Debug')
    variables:
      _HelixBuildConfig: $(_BuildConfig)
      # Run build in docker container
      _PREVIEW_VSTS_DOCKER_IMAGE: microsoft/dotnet-buildtools-prereqs:ubuntu-14.04-cross-0cd4667-20170319080304
