# Sample VSTS CI file
variables:
  Build.Repository.Clean: true
  targetFramework: 'netcoreapp2.0'

phases:
  - phase: Windows
    queue:
      name: Helix
    variables:
      buildConfiguration: 'Release'
    steps:
    - template: eng/build.yml

  - phase: Linux
    queue:
      name: DotNetCore-Linux
    variables:
      buildConfiguration: 'Release'
    steps:
    - task: DotNetCoreInstaller@0
      displayName: Use .NET Core sdk 1.0.4
    - template: eng/build.yml