# Sample VSTS CI file
variables:
  Build.Repository.Clean: true
  targetFramework: netcoreapp2.0
  yamlDoThePublish: YesPlease

# Three phases for each of the three OSes we want to run on
phases:
  - phase: Windows
    queue:
      name: Helix
      parallel: 2
      matrix:
        debug_conf:
          _BuildConfig: Debug
        ${{ if notIn(variables['Build.Reason'], 'PullRequest') }}:
          release_conf:
            _BuildConfig: Release
    steps:
    - powershell: |
        echo $env:BuildConfig
        echo $env:YamlDoThePublish
      env:
        BuildConfig: $(_BuildConfig)
        YamlDoThePublish: $(yamlDoThePublish)
    - template: eng/build.yml
    - ${{ if eq(variables['yamlDoThePublish'], 'YesPlease') }}:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          projects: 'HelloWorld/HelloWorld.csproj'
          publishWebProjects: false
          arguments: '--configuration $(_BuildConfig) --output $(build.artifactStagingDirectory) --framework $(targetFramework)'
        displayName: dotnet publish

  - phase: OSX
    queue:
      name: Hosted macOS Preview
      parallel: 2
      matrix:
        debug_conf:
          _BuildConfig: Debug
        ${{ if notIn(variables['Build.Reason'], 'PullRequest') }}:
          release_conf:
            _BuildConfig: Release
    steps:
    - template: eng/build.yml

  - phase: Linux
    queue:
      name: DotNetCore-Linux
      parallel: 2
      matrix:
        debug_conf:
          _BuildConfig: Debug
        ${{ if notIn(variables['Build.Reason'], 'PullRequest') }}:
          release_conf:
            _BuildConfig: Release
    steps:
    - template: eng/build.yml