parameters:
  buildConfig: 'Debug'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    arguments: '-v diag'
  displayName: dotnet restore
  env:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    DOTNET_MULTILEVEL_LOOKUP: 0

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfig)'
  displayName: dotnet build

- ${{ if eq(parameters.buildConfig, 'Release') }}:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: 'HelloWorld/HelloWorld.csproj'
      publishWebProjects: false
      arguments: '--configuration $(buildConfig) --output $(build.artifactStagingDirectory) --framework $(targetFramework)'
    displayName: dotnet publish